apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: file-sharing
data:
  BASE_URL: "http://api.fileshare.local"
  ALLOWED_ORIGINS: "http://fileshare.local"
  STORAGE_PATH: "/app/uploads"
  DB_URL: "jdbc:postgresql://postgres-service:5432/filesharingdb"
  DB_USERNAME: "postgres"
